# Generated by Django 2.0.4 on 2018-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20180426_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(),
        ),
    ]
